import { Container, Review } from "../../../components/shared/layout";
import { Nav } from "../../../components/shared/profile";
import { Metadata } from "next";
import Style from "../../../components/shared/profile/profile.module.scss";

const metadata: Metadata = {
  title: "GREENSHOP | Profile Page",
  description: "Generated by create next app",
};

export default async function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className={Style.profile}>
      <div className="container">
        <Container>
          <Review summaryWidth title="My Account">
            <Nav />
          </Review>

          {children}
        </Container>
      </div>
    </section>
  );
}
