import { Metadata } from "next";

import Header from "../../components/shared/header";
import Footer from "../../components/shared/footer";
import React from "react";

const metadata: Metadata = {
  title: "GREENSHOP | Main Page",
  description: "Generated by create next app",
};

const MainLayout = ({
  children,
  modal,
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) => {
  return (
    <main>
      <Header />

      {modal}

      {children}

      <Footer />
    </main>
  );
};

export default MainLayout;
